package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.dto.client.AuthorDto;
import mta.ltnc.BookStore.entity.Author;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface AuthorRepository extends JpaRepository<Author, Integer>, JpaSpecificationExecutor<Author> {
    List<Author> findAllByAuthorType(Integer authorType);
    List<Author> findTop5ByAuthorType(Integer authorType);
    @Query("SELECT new mta.ltnc.BookStore.dto.client.AuthorDto(a,COUNT(a.name)) FROM Author a LEFT JOIN Book b ON a = b.author where a.authorType.id = :authorType GROUP BY a")
    List<AuthorDto> getAllAuthorDtoByAuthorType(@Param("authorType")Long authorType);
}
