package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.dto.client.CartItemDto;
import mta.ltnc.BookStore.entity.CartItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface CartItemRepository extends JpaRepository<CartItem, Integer>, JpaSpecificationExecutor<CartItem> {
    @Query("SELECT new mta.ltnc.BookStore.dto.client.CartItemDto(c) FROM CartItem c WHERE c.user.id = :userId")
    List<CartItemDto> getAllByUserId(@Param("userId")Long userId);

    @Modifying(clearAutomatically = true)
    @Query("UPDATE CartItem ci set ci.quantity =:quantity where ci.book.id = :itemId AND ci.user.id = :userId")
    void updateQuantity(@Param("quantity") Integer quantity, @Param("itemId") Long itemId,@Param("userId") Long userId);

    @Query("SELECT ci FROM CartItem ci WHERE ci.book.id = :itemId AND ci.user.id = :userId")
    CartItem findByItemIdAndUserId(@Param("itemId")Long itemId,@Param("userId")Long userId);

    void deleteByBook_IdAndUser_Id(Long itemId, Long userId);
}
