package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.dto.client.OrderDto;
import mta.ltnc.BookStore.entity.Order;
import mta.ltnc.BookStore.entity.StatusOrder;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.sql.Date;
import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface OrderRepository extends JpaRepository<Order, Long>, JpaSpecificationExecutor<Order> {
//
    List<Order> findAllByCreatedDateBetween(Date start, Date end);
    List<OrderDto> findAllByUserId(Long userId);

    Order findTop1ByCode(String code);
    Long countAllByStatusOrder(StatusOrder statusOrder);
}
