package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.dto.client.OrderDetailDto;
import mta.ltnc.BookStore.entity.OrderDetail;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface OrderDetailRepository extends JpaRepository<OrderDetail, Integer>, JpaSpecificationExecutor<OrderDetail> {

    @Query("SELECT od FROM OrderDetail od where od.order.id = :orderId")
    List<OrderDetail> findAllByOrderId(@Param("orderId") Long orderId);
    @Query("SELECT new mta.ltnc.BookStore.dto.client.OrderDetailDto(od) FROM OrderDetail od WHERE od.order.id = :orderId")
    List<OrderDetailDto> getAllByOrderId(@Param("orderId") Long orderId);
}
