package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {

    @Query("SELECT u FROM User u WHERE u.userName LIKE %:term% or u.email LIKE %:term%")
    List<User> findUserByEmailOrUserName(@Param("term") String term);

    User findByUserNameOrEmailAndPassword(String userName, String email,String password);
    
    User findByEmail(String email);

    User findByUserName(String username);

    User findByUserNameAndPassword(String username, String password);
}
