package mta.ltnc.BookStore.repositories;

import mta.ltnc.BookStore.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Repository
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {

    User findByUserNameOrEmailAndPassword(String userName, String email,String password);
    
    User findByEmail(String email);

    User findByUserName(String username);

    User findByUserNameAndPassword(String username, String password);
}
