package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.AuthorType;
import mta.ltnc.BookStore.repositories.AuthorTypeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class AuthorTypeManager {

	private AuthorTypeRepository authorTypeRepository;

	@Autowired
	public AuthorTypeManager(AuthorTypeRepository authorTypeRepository) {
		this.authorTypeRepository = authorTypeRepository;
	}

}
