package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Book;
import mta.ltnc.BookStore.repositories.BookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class BookManager {

	private BookRepository bookRepository;

	@Autowired
	public BookManager(BookRepository bookRepository) {
		this.bookRepository = bookRepository;
	}

}
