package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.BookImage;
import mta.ltnc.BookStore.repositories.BookImageRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class BookImageManager {

	private BookImageRepository bookImageRepository;

	@Autowired
	public BookImageManager(BookImageRepository bookImageRepository) {
		this.bookImageRepository = bookImageRepository;
	}

}
