package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Category;
import mta.ltnc.BookStore.repositories.CategoryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class CategoryManager {

	private CategoryRepository categoryRepository;

	@Autowired
	public CategoryManager(CategoryRepository categoryRepository) {
		this.categoryRepository = categoryRepository;
	}

}
