package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Feedback;
import mta.ltnc.BookStore.repositories.FeedbackRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class FeedbackManager {

	private FeedbackRepository feedbackRepository;

	@Autowired
	public FeedbackManager(FeedbackRepository feedbackRepository) {
		this.feedbackRepository = feedbackRepository;
	}

}
