package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Order;
import mta.ltnc.BookStore.repositories.OrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class OrderManager {

	private OrderRepository orderRepository;

	@Autowired
	public OrderManager(OrderRepository orderRepository) {
		this.orderRepository = orderRepository;
	}

}
