package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.OrderDetail;
import mta.ltnc.BookStore.repositories.OrderDetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class OrderDetailManager {

	private OrderDetailRepository orderDetailRepository;

	@Autowired
	public OrderDetailManager(OrderDetailRepository orderDetailRepository) {
		this.orderDetailRepository = orderDetailRepository;
	}

}
