package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Publisher;
import mta.ltnc.BookStore.repositories.PublisherRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class PublisherManager {

	private PublisherRepository publisherRepository;

	@Autowired
	public PublisherManager(PublisherRepository publisherRepository) {
		this.publisherRepository = publisherRepository;
	}

}
