package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.PurchaseDetail;
import mta.ltnc.BookStore.repositories.PurchaseDetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class PurchaseDetailManager {

	private PurchaseDetailRepository purchaseDetailRepository;

	@Autowired
	public PurchaseDetailManager(PurchaseDetailRepository purchaseDetailRepository) {
		this.purchaseDetailRepository = purchaseDetailRepository;
	}

}
