package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Purchase;
import mta.ltnc.BookStore.repositories.PurchaseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class PurchaseManager {

	private PurchaseRepository purchaseRepository;

	@Autowired
	public PurchaseManager(PurchaseRepository purchaseRepository) {
		this.purchaseRepository = purchaseRepository;
	}

}
