package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.Slide;
import mta.ltnc.BookStore.repositories.SlideRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class SlideManager {

	private SlideRepository slideRepository;

	@Autowired
	public SlideManager(SlideRepository slideRepository) {
		this.slideRepository = slideRepository;
	}

}
