package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.StatusOrder;
import mta.ltnc.BookStore.repositories.StatusOrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class StatusOrderManager {

	private StatusOrderRepository statusOrderRepository;

	@Autowired
	public StatusOrderManager(StatusOrderRepository statusOrderRepository) {
		this.statusOrderRepository = statusOrderRepository;
	}

}
