package mta.ltnc.BookStore.managers;

import mta.ltnc.BookStore.entity.UserGroupRole;
import mta.ltnc.BookStore.repositories.UserGroupRoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 22/06/2019
*/
@Component
public class UserGroupRoleManager {

	private UserGroupRoleRepository userGroupRoleRepository;

	@Autowired
	public UserGroupRoleManager(UserGroupRoleRepository userGroupRoleRepository) {
		this.userGroupRoleRepository = userGroupRoleRepository;
	}

}
